title: "Silly Little Ding Dongs"
description: "is a very unserious podcast about everything that makes Lisa Lorraine Carson catatonic with delight."
url: "https://sillylittledingdongs.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Banner image
banner: "/assets/images/banner.png"

# Listen links
listen:
  - title: "Apple Podcasts"
    url: "https://podcasts.apple.com/us/podcast/silly-little-ding-dongs/id1732929956"
  - title: "Spotify Podcasts"
    url: "https://open.spotify.com/show/0HXu5eCPoAJwH6YMfkKN2f"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
