title: "Silly Little Ding Dongs"
description: "is a very unserious podcast about everything that makes Lisa Lorraine Carson catatonic with delight."
url: "https://sillylittledingdongs.com"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Banner image
banner: "/assets/images/banner.png"

# Listen links
listen:
  - title: "Apple Podcasts"
    url: "#"
  - title: "Spotify Podcasts"
    url: "#"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
